language: cpp
compiler:
  - gcc
notifications:
  email: false
before_script: 
  - "whoami"
  - "[System.IO.File]::WriteAllText(\"C:/MinGW/msys/1.0/etc/fstab\",\"C:/MinGW /mingw\")"
script: "echo test"
