language: cpp
compiler:
  - gcc
notifications:
  email: false
before_script: 
  - "whoami"
  - "[System.IO.File]::WriteAllText(\"C:/MinGW/msys/1.0/etc/fstab\",\"C:/MinGW /mingw\")"
script: "C:/MinGW/msys/1.0/bin/bash.exe -i -c \"echo $PATH && mv /c/Git/bin/git.exe /c/Git && rm /c/Git/bin/msys-*.dll && rm /c/Git/bin/*.exe && mv /c/Git/git.exe /c/Git/bin && ls -la /c/Git/bin && cd /c/ && which perl && git clone https://github.com/loladiro/julia.git && cd julia && make\""

