language: cpp
compiler:
  - gcc
notifications:
  email: false
before_script: 
  - "whoami"
  - "[System.IO.File]::WriteAllText(\"C:/MinGW/msys/1.0/etc/fstab\",\"C:/MinGW /mingw`nC:/Git /git\")"
  - "$env:PATH"
script: "C:/MinGW/msys/1.0/bin/bash.exe -i -c \"export PATH=.:/usr/local/bin:/bin:/mingw/bin:/git/bin:`$PATH && export GIT_EXEC_PATH=/git/libexec/git-core && mv /c/Git/bin/git.exe /c/Git && rm /c/Git/bin/msys-*.dll && mv /c/Git/git.exe /c/Git/bin && cd /c/ && /usr/bin/sed --version && git clone --quiet https://github.com/loladiro/julia.git && cd julia && make\""

