language: cpp
compiler:
  - gcc
notifications:
  email: false
script: C:/MinGW/msys/1.0/bin/bash.exe -i -c "export PATH=$PATH:/c/Git/bin && cd /c/ && git clone https://github.com/loladiro/julia.git && make"
